"""empty message

Revision ID: 59abaa98ef4a
Revises: 7edd89ab2755
Create Date: 2022-04-21 08:45:19.598550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59abaa98ef4a'
down_revision = '7edd89ab2755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update', sa.Column('week', sa.Integer(), nullable=True))
    op.add_column('update', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('update', 'year')
    op.drop_column('update', 'week')
    # ### end Alembic commands ###
